################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../src/hal/src/stm32f7xx_hal.c \
../src/hal/src/stm32f7xx_hal_adc.c \
../src/hal/src/stm32f7xx_hal_adc_ex.c \
../src/hal/src/stm32f7xx_hal_can.c \
../src/hal/src/stm32f7xx_hal_cec.c \
../src/hal/src/stm32f7xx_hal_cortex.c \
../src/hal/src/stm32f7xx_hal_crc.c \
../src/hal/src/stm32f7xx_hal_crc_ex.c \
../src/hal/src/stm32f7xx_hal_cryp.c \
../src/hal/src/stm32f7xx_hal_cryp_ex.c \
../src/hal/src/stm32f7xx_hal_dac.c \
../src/hal/src/stm32f7xx_hal_dac_ex.c \
../src/hal/src/stm32f7xx_hal_dcmi.c \
../src/hal/src/stm32f7xx_hal_dcmi_ex.c \
../src/hal/src/stm32f7xx_hal_dfsdm.c \
../src/hal/src/stm32f7xx_hal_dma.c \
../src/hal/src/stm32f7xx_hal_dma2d.c \
../src/hal/src/stm32f7xx_hal_dma_ex.c \
../src/hal/src/stm32f7xx_hal_dsi.c \
../src/hal/src/stm32f7xx_hal_eth.c \
../src/hal/src/stm32f7xx_hal_flash.c \
../src/hal/src/stm32f7xx_hal_flash_ex.c \
../src/hal/src/stm32f7xx_hal_gpio.c \
../src/hal/src/stm32f7xx_hal_hash.c \
../src/hal/src/stm32f7xx_hal_hash_ex.c \
../src/hal/src/stm32f7xx_hal_hcd.c \
../src/hal/src/stm32f7xx_hal_i2c.c \
../src/hal/src/stm32f7xx_hal_i2c_ex.c \
../src/hal/src/stm32f7xx_hal_i2s.c \
../src/hal/src/stm32f7xx_hal_irda.c \
../src/hal/src/stm32f7xx_hal_iwdg.c \
../src/hal/src/stm32f7xx_hal_jpeg.c \
../src/hal/src/stm32f7xx_hal_lptim.c \
../src/hal/src/stm32f7xx_hal_ltdc.c \
../src/hal/src/stm32f7xx_hal_ltdc_ex.c \
../src/hal/src/stm32f7xx_hal_mdios.c \
../src/hal/src/stm32f7xx_hal_mmc.c \
../src/hal/src/stm32f7xx_hal_nand.c \
../src/hal/src/stm32f7xx_hal_nor.c \
../src/hal/src/stm32f7xx_hal_pcd.c \
../src/hal/src/stm32f7xx_hal_pcd_ex.c \
../src/hal/src/stm32f7xx_hal_pwr.c \
../src/hal/src/stm32f7xx_hal_pwr_ex.c \
../src/hal/src/stm32f7xx_hal_qspi.c \
../src/hal/src/stm32f7xx_hal_rcc.c \
../src/hal/src/stm32f7xx_hal_rcc_ex.c \
../src/hal/src/stm32f7xx_hal_rng.c \
../src/hal/src/stm32f7xx_hal_rtc.c \
../src/hal/src/stm32f7xx_hal_rtc_ex.c \
../src/hal/src/stm32f7xx_hal_sai.c \
../src/hal/src/stm32f7xx_hal_sai_ex.c \
../src/hal/src/stm32f7xx_hal_sd.c \
../src/hal/src/stm32f7xx_hal_sdram.c \
../src/hal/src/stm32f7xx_hal_smartcard.c \
../src/hal/src/stm32f7xx_hal_smartcard_ex.c \
../src/hal/src/stm32f7xx_hal_smbus.c \
../src/hal/src/stm32f7xx_hal_spdifrx.c \
../src/hal/src/stm32f7xx_hal_spi.c \
../src/hal/src/stm32f7xx_hal_sram.c \
../src/hal/src/stm32f7xx_hal_tim.c \
../src/hal/src/stm32f7xx_hal_tim_ex.c \
../src/hal/src/stm32f7xx_hal_uart.c \
../src/hal/src/stm32f7xx_hal_usart.c \
../src/hal/src/stm32f7xx_hal_wwdg.c \
../src/hal/src/stm32f7xx_ll_adc.c \
../src/hal/src/stm32f7xx_ll_crc.c \
../src/hal/src/stm32f7xx_ll_dac.c \
../src/hal/src/stm32f7xx_ll_dma.c \
../src/hal/src/stm32f7xx_ll_dma2d.c \
../src/hal/src/stm32f7xx_ll_exti.c \
../src/hal/src/stm32f7xx_ll_fmc.c \
../src/hal/src/stm32f7xx_ll_gpio.c \
../src/hal/src/stm32f7xx_ll_i2c.c \
../src/hal/src/stm32f7xx_ll_lptim.c \
../src/hal/src/stm32f7xx_ll_pwr.c \
../src/hal/src/stm32f7xx_ll_rcc.c \
../src/hal/src/stm32f7xx_ll_rng.c \
../src/hal/src/stm32f7xx_ll_rtc.c \
../src/hal/src/stm32f7xx_ll_sdmmc.c \
../src/hal/src/stm32f7xx_ll_spi.c \
../src/hal/src/stm32f7xx_ll_tim.c \
../src/hal/src/stm32f7xx_ll_usart.c \
../src/hal/src/stm32f7xx_ll_usb.c \
../src/hal/src/stm32f7xx_ll_utils.c 

OBJS += \
./src/hal/src/stm32f7xx_hal.o \
./src/hal/src/stm32f7xx_hal_adc.o \
./src/hal/src/stm32f7xx_hal_adc_ex.o \
./src/hal/src/stm32f7xx_hal_can.o \
./src/hal/src/stm32f7xx_hal_cec.o \
./src/hal/src/stm32f7xx_hal_cortex.o \
./src/hal/src/stm32f7xx_hal_crc.o \
./src/hal/src/stm32f7xx_hal_crc_ex.o \
./src/hal/src/stm32f7xx_hal_cryp.o \
./src/hal/src/stm32f7xx_hal_cryp_ex.o \
./src/hal/src/stm32f7xx_hal_dac.o \
./src/hal/src/stm32f7xx_hal_dac_ex.o \
./src/hal/src/stm32f7xx_hal_dcmi.o \
./src/hal/src/stm32f7xx_hal_dcmi_ex.o \
./src/hal/src/stm32f7xx_hal_dfsdm.o \
./src/hal/src/stm32f7xx_hal_dma.o \
./src/hal/src/stm32f7xx_hal_dma2d.o \
./src/hal/src/stm32f7xx_hal_dma_ex.o \
./src/hal/src/stm32f7xx_hal_dsi.o \
./src/hal/src/stm32f7xx_hal_eth.o \
./src/hal/src/stm32f7xx_hal_flash.o \
./src/hal/src/stm32f7xx_hal_flash_ex.o \
./src/hal/src/stm32f7xx_hal_gpio.o \
./src/hal/src/stm32f7xx_hal_hash.o \
./src/hal/src/stm32f7xx_hal_hash_ex.o \
./src/hal/src/stm32f7xx_hal_hcd.o \
./src/hal/src/stm32f7xx_hal_i2c.o \
./src/hal/src/stm32f7xx_hal_i2c_ex.o \
./src/hal/src/stm32f7xx_hal_i2s.o \
./src/hal/src/stm32f7xx_hal_irda.o \
./src/hal/src/stm32f7xx_hal_iwdg.o \
./src/hal/src/stm32f7xx_hal_jpeg.o \
./src/hal/src/stm32f7xx_hal_lptim.o \
./src/hal/src/stm32f7xx_hal_ltdc.o \
./src/hal/src/stm32f7xx_hal_ltdc_ex.o \
./src/hal/src/stm32f7xx_hal_mdios.o \
./src/hal/src/stm32f7xx_hal_mmc.o \
./src/hal/src/stm32f7xx_hal_nand.o \
./src/hal/src/stm32f7xx_hal_nor.o \
./src/hal/src/stm32f7xx_hal_pcd.o \
./src/hal/src/stm32f7xx_hal_pcd_ex.o \
./src/hal/src/stm32f7xx_hal_pwr.o \
./src/hal/src/stm32f7xx_hal_pwr_ex.o \
./src/hal/src/stm32f7xx_hal_qspi.o \
./src/hal/src/stm32f7xx_hal_rcc.o \
./src/hal/src/stm32f7xx_hal_rcc_ex.o \
./src/hal/src/stm32f7xx_hal_rng.o \
./src/hal/src/stm32f7xx_hal_rtc.o \
./src/hal/src/stm32f7xx_hal_rtc_ex.o \
./src/hal/src/stm32f7xx_hal_sai.o \
./src/hal/src/stm32f7xx_hal_sai_ex.o \
./src/hal/src/stm32f7xx_hal_sd.o \
./src/hal/src/stm32f7xx_hal_sdram.o \
./src/hal/src/stm32f7xx_hal_smartcard.o \
./src/hal/src/stm32f7xx_hal_smartcard_ex.o \
./src/hal/src/stm32f7xx_hal_smbus.o \
./src/hal/src/stm32f7xx_hal_spdifrx.o \
./src/hal/src/stm32f7xx_hal_spi.o \
./src/hal/src/stm32f7xx_hal_sram.o \
./src/hal/src/stm32f7xx_hal_tim.o \
./src/hal/src/stm32f7xx_hal_tim_ex.o \
./src/hal/src/stm32f7xx_hal_uart.o \
./src/hal/src/stm32f7xx_hal_usart.o \
./src/hal/src/stm32f7xx_hal_wwdg.o \
./src/hal/src/stm32f7xx_ll_adc.o \
./src/hal/src/stm32f7xx_ll_crc.o \
./src/hal/src/stm32f7xx_ll_dac.o \
./src/hal/src/stm32f7xx_ll_dma.o \
./src/hal/src/stm32f7xx_ll_dma2d.o \
./src/hal/src/stm32f7xx_ll_exti.o \
./src/hal/src/stm32f7xx_ll_fmc.o \
./src/hal/src/stm32f7xx_ll_gpio.o \
./src/hal/src/stm32f7xx_ll_i2c.o \
./src/hal/src/stm32f7xx_ll_lptim.o \
./src/hal/src/stm32f7xx_ll_pwr.o \
./src/hal/src/stm32f7xx_ll_rcc.o \
./src/hal/src/stm32f7xx_ll_rng.o \
./src/hal/src/stm32f7xx_ll_rtc.o \
./src/hal/src/stm32f7xx_ll_sdmmc.o \
./src/hal/src/stm32f7xx_ll_spi.o \
./src/hal/src/stm32f7xx_ll_tim.o \
./src/hal/src/stm32f7xx_ll_usart.o \
./src/hal/src/stm32f7xx_ll_usb.o \
./src/hal/src/stm32f7xx_ll_utils.o 

C_DEPS += \
./src/hal/src/stm32f7xx_hal.d \
./src/hal/src/stm32f7xx_hal_adc.d \
./src/hal/src/stm32f7xx_hal_adc_ex.d \
./src/hal/src/stm32f7xx_hal_can.d \
./src/hal/src/stm32f7xx_hal_cec.d \
./src/hal/src/stm32f7xx_hal_cortex.d \
./src/hal/src/stm32f7xx_hal_crc.d \
./src/hal/src/stm32f7xx_hal_crc_ex.d \
./src/hal/src/stm32f7xx_hal_cryp.d \
./src/hal/src/stm32f7xx_hal_cryp_ex.d \
./src/hal/src/stm32f7xx_hal_dac.d \
./src/hal/src/stm32f7xx_hal_dac_ex.d \
./src/hal/src/stm32f7xx_hal_dcmi.d \
./src/hal/src/stm32f7xx_hal_dcmi_ex.d \
./src/hal/src/stm32f7xx_hal_dfsdm.d \
./src/hal/src/stm32f7xx_hal_dma.d \
./src/hal/src/stm32f7xx_hal_dma2d.d \
./src/hal/src/stm32f7xx_hal_dma_ex.d \
./src/hal/src/stm32f7xx_hal_dsi.d \
./src/hal/src/stm32f7xx_hal_eth.d \
./src/hal/src/stm32f7xx_hal_flash.d \
./src/hal/src/stm32f7xx_hal_flash_ex.d \
./src/hal/src/stm32f7xx_hal_gpio.d \
./src/hal/src/stm32f7xx_hal_hash.d \
./src/hal/src/stm32f7xx_hal_hash_ex.d \
./src/hal/src/stm32f7xx_hal_hcd.d \
./src/hal/src/stm32f7xx_hal_i2c.d \
./src/hal/src/stm32f7xx_hal_i2c_ex.d \
./src/hal/src/stm32f7xx_hal_i2s.d \
./src/hal/src/stm32f7xx_hal_irda.d \
./src/hal/src/stm32f7xx_hal_iwdg.d \
./src/hal/src/stm32f7xx_hal_jpeg.d \
./src/hal/src/stm32f7xx_hal_lptim.d \
./src/hal/src/stm32f7xx_hal_ltdc.d \
./src/hal/src/stm32f7xx_hal_ltdc_ex.d \
./src/hal/src/stm32f7xx_hal_mdios.d \
./src/hal/src/stm32f7xx_hal_mmc.d \
./src/hal/src/stm32f7xx_hal_nand.d \
./src/hal/src/stm32f7xx_hal_nor.d \
./src/hal/src/stm32f7xx_hal_pcd.d \
./src/hal/src/stm32f7xx_hal_pcd_ex.d \
./src/hal/src/stm32f7xx_hal_pwr.d \
./src/hal/src/stm32f7xx_hal_pwr_ex.d \
./src/hal/src/stm32f7xx_hal_qspi.d \
./src/hal/src/stm32f7xx_hal_rcc.d \
./src/hal/src/stm32f7xx_hal_rcc_ex.d \
./src/hal/src/stm32f7xx_hal_rng.d \
./src/hal/src/stm32f7xx_hal_rtc.d \
./src/hal/src/stm32f7xx_hal_rtc_ex.d \
./src/hal/src/stm32f7xx_hal_sai.d \
./src/hal/src/stm32f7xx_hal_sai_ex.d \
./src/hal/src/stm32f7xx_hal_sd.d \
./src/hal/src/stm32f7xx_hal_sdram.d \
./src/hal/src/stm32f7xx_hal_smartcard.d \
./src/hal/src/stm32f7xx_hal_smartcard_ex.d \
./src/hal/src/stm32f7xx_hal_smbus.d \
./src/hal/src/stm32f7xx_hal_spdifrx.d \
./src/hal/src/stm32f7xx_hal_spi.d \
./src/hal/src/stm32f7xx_hal_sram.d \
./src/hal/src/stm32f7xx_hal_tim.d \
./src/hal/src/stm32f7xx_hal_tim_ex.d \
./src/hal/src/stm32f7xx_hal_uart.d \
./src/hal/src/stm32f7xx_hal_usart.d \
./src/hal/src/stm32f7xx_hal_wwdg.d \
./src/hal/src/stm32f7xx_ll_adc.d \
./src/hal/src/stm32f7xx_ll_crc.d \
./src/hal/src/stm32f7xx_ll_dac.d \
./src/hal/src/stm32f7xx_ll_dma.d \
./src/hal/src/stm32f7xx_ll_dma2d.d \
./src/hal/src/stm32f7xx_ll_exti.d \
./src/hal/src/stm32f7xx_ll_fmc.d \
./src/hal/src/stm32f7xx_ll_gpio.d \
./src/hal/src/stm32f7xx_ll_i2c.d \
./src/hal/src/stm32f7xx_ll_lptim.d \
./src/hal/src/stm32f7xx_ll_pwr.d \
./src/hal/src/stm32f7xx_ll_rcc.d \
./src/hal/src/stm32f7xx_ll_rng.d \
./src/hal/src/stm32f7xx_ll_rtc.d \
./src/hal/src/stm32f7xx_ll_sdmmc.d \
./src/hal/src/stm32f7xx_ll_spi.d \
./src/hal/src/stm32f7xx_ll_tim.d \
./src/hal/src/stm32f7xx_ll_usart.d \
./src/hal/src/stm32f7xx_ll_usb.d \
./src/hal/src/stm32f7xx_ll_utils.d 


# Each subdirectory must supply rules for building sources it contributes
src/hal/src/%.o: ../src/hal/src/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -mcpu=cortex-m7 -O3 -fmessage-length=0 -ffunction-sections -fdata-sections -ffreestanding -fno-builtin -Wunused -Wuninitialized -Wall -Wextra -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -Wno-sign-compare -DSTM32F746xx -I../src/cmsis -I../src/cmsis_boot -I../src/kiss/inc -I../src/usart_lib -I../src/cmsis_lib/include_inline -I../src -I../src/hal/include -I../src/img_data -I../src/BSP -std=gnu11 -Wbad-function-cast -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


